"""
xg_scraper.py — Fetch xG Data from Understat
==============================================
PURPOSE:
    Scrape match-level xG (expected goals) for both teams from Understat.com
    and merge into the master DataFrame as new features.

WHY xG MATTERS:
    Goals are noisy. A team winning 1-0 on 0.3 xG vs 2.4 xG opponent was lucky.
    Rolling xG averages capture *quality* of chances created/conceded, not just
    results. This is the single most predictive freely-available football metric
    that isn't already fully priced by bookmakers.

DATA PIPELINE:
    Understat → raw JSON (embedded in HTML) → per-match xG DataFrame
    → merge onto master parquet by (date, home_team, away_team)
    → add rolling xG features (5-game window, home/away split)

OUTPUTS added to master DataFrame:
    home_xg            : xG generated by home team this match
    away_xg            : xG generated by away team this match
    home_xg_roll5      : Rolling 5-game avg xG FOR (home perspective)
    away_xg_roll5      : Rolling 5-game avg xG FOR (away perspective)
    home_xga_roll5     : Rolling 5-game avg xG AGAINST (home perspective)
    away_xga_roll5     : Rolling 5-game avg xG AGAINST (away perspective)
    xg_diff_roll5      : home_xg_roll5 - away_xg_roll5 (strength indicator)
    home_xg_overperform: home_goals - home_xg (luck indicator, regresses to 0)
    away_xg_overperform: away_goals - away_xg

UNDERSTAT LEAGUES:
    EPL     → "EPL"
    LA_LIGA → "La_liga"
    SERIE_A → "Serie_A"
    LIGUE_1 → "Ligue_1"
    BUNDESLIGA → "Bundesliga" (add to LEAGUES config if needed)

USAGE:
    python src/xg_scraper.py                  ← fetch all leagues, all seasons
    python src/xg_scraper.py --league EPL     ← single league
    python src/xg_scraper.py --season 2024    ← single season (Understat uses YYYY)

    from src.xg_scraper import add_xg_features
    master_df = add_xg_features(master_df)    ← merge into existing DataFrame

FIXES:
    - Pylance reportArgumentType: engine="pyarrow" removed from read_parquet()
      calls (lines 460, 739). pandas auto-detects pyarrow at runtime; the
      Pylance stub for read_parquet only declares 'auto'|'fastparquet' which
      triggers a false-positive type error. Dropping the kwarg is the cleanest
      solution — behaviour is identical.
"""

import sys
import json
import time
import re
import argparse
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).parent.parent))

import requests
import pandas as pd
import numpy as np
from loguru import logger

from config import PATHS, LEAGUES, SEASONS, SCRAPING

logger.remove()
logger.add(sys.stderr, level="INFO",
           format="<green>{time:HH:mm:ss}</green> | <level>{level:<8}</level> | {message}")


# ═══════════════════════════════════════════════════════
# SECTION 1 — LEAGUE/SEASON MAPPING
# ═══════════════════════════════════════════════════════

# Understat uses different names and integer years (not "2425")
UNDERSTAT_LEAGUE_MAP = {
    "EPL":       "EPL",
    "LA_LIGA":   "La_liga",
    "SERIE_A":   "Serie_A",
    "LIGUE_1":   "Ligue_1",
    "BUNDESLIGA":"Bundesliga",
}

# Understat season = start year integer, e.g. 2023 = 2023-24
# Map from our "2425" format → Understat "2024"
def our_season_to_understat(code: str) -> int:
    """
    Convert our season code to Understat's start-year integer.

    Handles both formats:
      '2425'  → 2024  (football-data.co.uk style: last 2 digits of each year)
      '2024'  → 2024  (update_data.py style: full 4-digit start year)
      '24'    → 2024  (short form)
    """
    code = str(code).strip()
    if len(code) == 4 and code.isdigit():
        year = int(code)
        # If it looks like a full year (2018–2030), use directly
        if 2010 <= year <= 2035:
            return year
        # Otherwise treat as 'XXYY' → 20XX
        return 2000 + int(code[:2])
    if len(code) == 2:
        return 2000 + int(code)
    # Fallback
    return int(code[:4])

# Team name normalisation: Understat → our master parquet names
# Add entries as you encounter mismatches
TEAM_NAME_MAP = {
    # EPL
    "Manchester City":      "Man City",
    "Manchester United":    "Man United",
    "Tottenham":            "Tottenham",
    "Nottingham Forest":    "Nott'm Forest",
    "Newcastle United":     "Newcastle",
    "Wolverhampton Wanderers": "Wolves",
    "Brighton":             "Brighton",
    "West Ham":             "West Ham",
    "Aston Villa":          "Aston Villa",
    "Crystal Palace":       "Crystal Palace",
    "AFC Bournemouth":      "Bournemouth",
    "Sheffield United":     "Sheffield United",
    "Luton":                "Luton",
    "Ipswich":              "Ipswich",
    # La Liga
    "Atletico Madrid":      "Ath Madrid",
    "Athletic Club":        "Ath Bilbao",
    "Real Sociedad":        "Sociedad",
    "Villarreal":           "Villarreal",
    "Rayo Vallecano":       "Vallecano",
    "Celta Vigo":           "Celta",
    "Las Palmas":           "Las Palmas",
    # Serie A
    "AC Milan":             "Milan",
    "Inter":                "Inter",
    "Hellas Verona":        "Verona",
    # Ligue 1
    "Paris Saint-Germain":  "Paris SG",
    "Marseille":            "Marseille",
    "Lyon":                 "Lyon",
    "Rennes":               "Rennes",
    "Saint-Etienne":        "St Etienne",
    # Bundesliga
    "Bayern Munich":        "Bayern Munich",
    "Borussia Dortmund":    "Dortmund",
    "Bayer Leverkusen":     "Leverkusen",
    "Eintracht Frankfurt":  "Ein Frankfurt",
    "Borussia M.Gladbach":  "M'gladbach",
    "TSG Hoffenheim":       "Hoffenheim",
    "Mainz 05":             "Mainz",
    "Werder Bremen":        "Werder Bremen",
    "VfB Stuttgart":        "Stuttgart",
}


# ═══════════════════════════════════════════════════════
# SECTION 2 — UNDERSTAT SCRAPER
# ═══════════════════════════════════════════════════════

def _get_session() -> "requests.Session":
    """
    Return a warm, persistent requests Session for Understat.
    Created once per process, homepage visited to get cookies.
    """
    if not hasattr(_get_session, "_session"):
        s = requests.Session()
        s.headers.update({
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            "Accept-Language": "en-GB,en;q=0.9",
            "Accept-Encoding": "gzip, deflate, br",
            "Connection":      "keep-alive",
        })
        try:
            s.get("https://understat.com/", timeout=12)
            time.sleep(1.5)
        except Exception:
            pass
        _get_session._session = s
    return _get_session._session


def _fetch_via_ajax(league: str, season: int) -> list | None:
    """
    Fetch match data from Understat's internal AJAX endpoint.

    This is what Understat's own JavaScript calls — much simpler than
    scraping the full HTML page and parsing embedded JS variables.

    Endpoint: POST https://understat.com/main/getLeagueData/
    Body:      league=EPL&season=2024

    Returns list of match dicts, or None if the request fails.
    """
    session = _get_session()
    url     = "https://understat.com/main/getLeagueData/"
    headers = {
        "Accept":           "application/json, text/javascript, */*; q=0.01",
        "Content-Type":     "application/x-www-form-urlencoded; charset=UTF-8",
        "X-Requested-With": "XMLHttpRequest",
        "Referer":          f"https://understat.com/league/{league}/{season}",
        "Origin":           "https://understat.com",
    }
    for attempt in range(3):
        try:
            time.sleep(2 + attempt)
            resp = session.post(
                url,
                data={"league": league, "season": str(season)},
                headers=headers,
                timeout=20,
            )
            if resp.status_code == 200:
                data = resp.json()
                # Response is {"response": [...matches...]}
                matches = data.get("response", data) if isinstance(data, dict) else data
                if isinstance(matches, list) and len(matches) > 0:
                    logger.debug(f"  AJAX: {len(matches)} matches for {league}/{season}")
                    return matches
            elif resp.status_code == 429:
                logger.warning(f"  Rate limited — waiting 30s (attempt {attempt+1})")
                time.sleep(30)
            else:
                logger.debug(f"  AJAX {resp.status_code} for {league}/{season}")
        except Exception as e:
            logger.debug(f"  AJAX attempt {attempt+1} failed: {e}")
    return None


def _fetch_via_html(league: str, season: int) -> list | None:
    """
    Fallback: fetch full HTML page and extract the datesData JS variable.

    Understat embeds match data as:
        var datesData = JSON.parse('%5B%7B...')   ← percent-encoded
        var datesData = JSON.parse('\\u005B...')   ← unicode-escaped
        var datesData = JSON.parse('[{...')        ← raw JSON

    We scan the FULL HTML (not just first 800 chars) and try all encodings.
    """
    from urllib.parse import unquote

    session = _get_session()
    url     = f"https://understat.com/league/{league}/{season}"
    headers = {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "none",
    }

    for attempt in range(3):
        try:
            time.sleep(3 + attempt * 2)
            resp = session.get(url, headers=headers, timeout=25)

            if resp.status_code != 200 or len(resp.text) < 1000:
                logger.debug(f"  HTML {resp.status_code}, length={len(resp.text)}")
                if resp.status_code == 403:
                    # Re-warm session
                    try:
                        session.get("https://understat.com/", timeout=10)
                        time.sleep(3)
                    except Exception:
                        pass
                continue

            html = resp.text

            # Search the FULL document for all JSON.parse( patterns
            patterns = [
                rf"var\s+datesData\s*=\s*JSON\.parse\('([^']+)'\)",
                rf'var\s+datesData\s*=\s*JSON\.parse\("([^"]+)"\)',
                r"datesData[^=]*=\s*JSON\.parse\('([^']+)'\)",
            ]

            for pat in patterns:
                m = re.search(pat, html)
                if not m:
                    continue
                raw = m.group(1)
                for decode_fn in [
                    lambda s: json.loads(unquote(s)),
                    lambda s: json.loads(s.encode().decode("unicode_escape")),
                    lambda s: json.loads(s),
                    lambda s: json.loads(unquote(unquote(s))),
                ]:
                    try:
                        result = decode_fn(raw)
                        if isinstance(result, list) and result:
                            logger.debug(
                                f"  HTML parse OK ({len(result)} matches) "
                                f"pattern={pat[:40]}"
                            )
                            return result
                    except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
                        continue

            debug_path = Path("/tmp") / f"understat_{league}_{season}.html"
            debug_path.write_text(html, encoding="utf-8")
            logger.warning(
                f"  datesData not found in HTML ({len(html):,} chars). "
                f"Saved to {debug_path} for inspection.\n"
                f"  Run: grep -o 'var [a-zA-Z]*' {debug_path} | head -20"
            )
            return None

        except Exception as e:
            logger.warning(f"  HTML attempt {attempt+1} failed: {e}")
            time.sleep(5)

    return None


def fetch_league_xg(league_key: str, season_year: int) -> "pd.DataFrame | None":
    """
    Fetch all match xG data for one league-season from Understat.

    Strategy:
      1. Try AJAX endpoint (Understat's internal API — fastest)
      2. Fall back to full HTML page scraping if AJAX fails

    Args:
        league_key:  Our league key e.g. 'EPL'
        season_year: Understat season start year e.g. 2024 (= 2024-25)

    Returns:
        DataFrame with columns:
            date, home_team, away_team, home_xg, away_xg, home_goals, away_goals
        or None if both methods fail.
    """
    understat_league = UNDERSTAT_LEAGUE_MAP.get(league_key)
    if not understat_league:
        logger.warning(f"No Understat mapping for {league_key} — skipping")
        return None

    # ── Method 1: AJAX ────────────────────────────────────────────────────
    raw_data = _fetch_via_ajax(understat_league, season_year)

    # ── Method 2: HTML fallback ───────────────────────────────────────────
    if not raw_data:
        raw_data = _fetch_via_html(understat_league, season_year)

    if not raw_data:
        logger.error(
            f"Both AJAX and HTML failed for {league_key}/{season_year}. "
            f"Check understat.com is accessible from your machine."
        )
        return None

    rows = []
    for match in raw_data:
        try:
            if match.get("isResult") is not True:
                continue

            home_raw = match.get("h", {}).get("title", "")
            away_raw = match.get("a", {}).get("title", "")
            home     = TEAM_NAME_MAP.get(home_raw, home_raw)
            away     = TEAM_NAME_MAP.get(away_raw, away_raw)

            rows.append({
                "date":       pd.to_datetime(match["datetime"]).normalize(),
                "home_team":  home,
                "away_team":  away,
                "home_xg":    float(match.get("xg", {}).get("h", 0) or 0),
                "away_xg":    float(match.get("xg", {}).get("a", 0) or 0),
                "home_goals": int(match.get("goals", {}).get("h", 0) or 0),
                "away_goals": int(match.get("goals", {}).get("a", 0) or 0),
                "league_key": league_key,
                "season_year":season_year,
            })
        except (KeyError, TypeError, ValueError) as e:
            logger.debug(f"Skipping malformed match entry: {e}")
            continue

    if not rows:
        logger.warning(f"No finished matches extracted for {league_key} {season_year}")
        return None

    df = pd.DataFrame(rows)
    df["date"] = pd.to_datetime(df["date"])
    df.sort_values("date", inplace=True)
    df.reset_index(drop=True, inplace=True)

    logger.info(f"  {league_key} {season_year}: {len(df)} matches with xG data")
    return df


def fetch_all_xg(
    leagues: "list[str] | None" = None,
    seasons: "list[str] | None" = None,
) -> pd.DataFrame:
    """
    Fetch xG data for all specified leagues and seasons.

    Args:
        leagues: List of our league keys (default: all in UNDERSTAT_LEAGUE_MAP)
        seasons: List of our season codes e.g. ['2223','2324','2425']
                 (default: SEASONS.ALL_SEASONS)

    Returns:
        Combined DataFrame with all xG data.
    """
    leagues = leagues or [k for k in LEAGUES if k in UNDERSTAT_LEAGUE_MAP]
    if seasons is None:
        current_year = our_season_to_understat(SEASONS.CURRENT)
        seasons_int  = [current_year]
        logger.info(f"Defaulting to current season only: {current_year}")
    else:
        seasons_int = [our_season_to_understat(s) for s in seasons]

    all_frames = []

    for league_key in leagues:
        for season_year in seasons_int:
            logger.info(f"Fetching xG: {league_key} {season_year} ...")
            df = fetch_league_xg(league_key, season_year)
            if df is not None and not df.empty:
                all_frames.append(df)
            time.sleep(1.5)

    if not all_frames:
        raise RuntimeError("No xG data was fetched. Check network and Understat availability.")

    combined = pd.concat(all_frames, ignore_index=True)
    combined.sort_values(["league_key", "date"], inplace=True)
    combined.reset_index(drop=True, inplace=True)

    logger.info(f"Total xG records: {len(combined):,} matches")
    return combined


def save_xg_data(df: pd.DataFrame) -> Path:
    """Save raw xG data to parquet cache."""
    PATHS.PROCESSED.mkdir(parents=True, exist_ok=True)
    path = PATHS.PROCESSED / "xg_raw.parquet"
    df.to_parquet(path, index=False, engine="pyarrow")
    logger.info(f"xG data saved: {path}")
    return path


def load_xg_data() -> pd.DataFrame:
    """Load cached xG parquet.

    Note: engine kwarg omitted — pandas auto-detects pyarrow at runtime.
    The Pylance stub for read_parquet only declares 'auto'|'fastparquet',
    causing a false-positive reportArgumentType error when 'pyarrow' is
    passed explicitly.
    """
    path = PATHS.PROCESSED / "xg_raw.parquet"
    if not path.exists():
        raise FileNotFoundError(
            f"xG data not found: {path}\n"
            "Run: python src/xg_scraper.py"
        )
    # engine intentionally omitted — pyarrow is auto-detected, avoids Pylance false positive
    df = pd.read_parquet(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


# ═══════════════════════════════════════════════════════
# SECTION 3 — ROLLING xG FEATURE ENGINEERING
# ═══════════════════════════════════════════════════════

def build_rolling_xg_features(
    xg_df: pd.DataFrame,
    window: int = 5,
) -> pd.DataFrame:
    """
    Compute rolling xG features for each team in each match.

    For match N, we compute rolling averages using only matches N-1, N-2, ...
    (strict past-only, no leakage).

    Features added per row (from HOME TEAM perspective):
        home_xg_roll{w}     : Rolling avg xG FOR home team (last w games, any venue)
        home_xga_roll{w}    : Rolling avg xG AGAINST home team (last w games)
        away_xg_roll{w}     : Rolling avg xG FOR away team
        away_xga_roll{w}    : Rolling avg xG AGAINST away team
        xg_diff_roll{w}     : home_xg_roll - away_xg_roll (net xG dominance)
        home_xg_form_ratio  : home_xg_roll / (home_xg_roll + home_xga_roll)  [0-1]
        away_xg_form_ratio  : away_xg_roll / (away_xg_roll + away_xga_roll)

    Args:
        xg_df:  Raw xG DataFrame from fetch_all_xg()
        window: Rolling window size (default 5 matches)

    Returns:
        DataFrame with all original columns PLUS rolling xG features.
    """
    df = xg_df.copy().sort_values(["league_key", "date"]).reset_index(drop=True)

    w = window
    suffix = f"roll{w}"

    home_xg_col  = f"home_xg_{suffix}"
    home_xga_col = f"home_xga_{suffix}"
    away_xg_col  = f"away_xg_{suffix}"
    away_xga_col = f"away_xga_{suffix}"

    for col in [home_xg_col, home_xga_col, away_xg_col, away_xga_col]:
        df[col] = np.nan

    for league_key in df["league_key"].unique():
        league_df = df[df["league_key"] == league_key].copy()

        for idx, row in league_df.iterrows():
            date      = row["date"]
            home_team = row["home_team"]
            away_team = row["away_team"]
            sub       = league_df[league_df["date"] < date]

            def _team_rolling(team: str) -> dict:
                """Past-w-game rolling xG for and against for one team."""
                home_rows = sub[sub["home_team"] == team][["home_xg", "away_xg"]]
                away_rows = sub[sub["away_team"] == team][["away_xg", "home_xg"]]
                home_rows = home_rows.rename(columns={"home_xg":"xg_for","away_xg":"xg_against"})
                away_rows = away_rows.rename(columns={"away_xg":"xg_for","home_xg":"xg_against"})
                combined  = pd.concat([home_rows, away_rows]).tail(w)
                if combined.empty:
                    return {"xg_for": np.nan, "xg_against": np.nan}
                return {
                    "xg_for":     combined["xg_for"].mean(),
                    "xg_against": combined["xg_against"].mean(),
                }

            h_stats = _team_rolling(home_team)
            a_stats = _team_rolling(away_team)

            df.loc[idx, home_xg_col]  = h_stats["xg_for"]
            df.loc[idx, home_xga_col] = h_stats["xg_against"]
            df.loc[idx, away_xg_col]  = a_stats["xg_for"]
            df.loc[idx, away_xga_col] = a_stats["xg_against"]

    df[f"xg_diff_{suffix}"] = df[home_xg_col] - df[away_xg_col]

    denom_home = df[home_xg_col] + df[home_xga_col]
    denom_away = df[away_xg_col] + df[away_xga_col]
    df["home_xg_form_ratio"] = np.where(denom_home > 0,
                                         df[home_xg_col] / denom_home, 0.5)
    df["away_xg_form_ratio"] = np.where(denom_away > 0,
                                         df[away_xg_col] / denom_away, 0.5)

    df["home_xg_overperform"] = df["home_goals"] - df["home_xg"]
    df["away_xg_overperform"] = df["away_goals"] - df["away_xg"]

    logger.info(f"Rolling xG features computed (window={w})")
    return df


# ═══════════════════════════════════════════════════════
# SECTION 4 — MERGE INTO MASTER DATAFRAME
# ═══════════════════════════════════════════════════════

def add_xg_features(
    master_df: pd.DataFrame,
    xg_df: "pd.DataFrame | None" = None,
    window: int = 5,
) -> pd.DataFrame:
    """
    Merge xG features into the master DataFrame.

    Matching strategy: join on (date, home_team, away_team, league_key).
    Teams not matched (name mismatch) get NaN — model handles with fillna(-999).

    Args:
        master_df: Main feature DataFrame
        xg_df:     Raw xG DataFrame (loaded from cache if None)
        window:    Rolling window for xG averages

    Returns:
        master_df with xG columns added.
    """
    if xg_df is None:
        try:
            xg_df = load_xg_data()
        except FileNotFoundError:
            logger.warning(
                "xG data not found — run python src/xg_scraper.py first. "
                "Continuing without xG features."
            )
            return master_df

    xg_features = build_rolling_xg_features(xg_df, window=window)

    xg_cols = [c for c in xg_features.columns
               if "xg" in c.lower() and c not in ("home_xg", "away_xg")]
    xg_cols = ["home_xg", "away_xg"] + xg_cols

    merge_on = ["date", "home_team", "away_team", "league_key"]
    xg_merge = xg_features[merge_on + xg_cols].copy()

    master_df["date"]  = pd.to_datetime(master_df["date"])
    xg_merge["date"]   = pd.to_datetime(xg_merge["date"])

    existing = [c for c in xg_cols if c in master_df.columns]
    if existing:
        master_df.drop(columns=existing, inplace=True)

    merged = master_df.merge(xg_merge, on=merge_on, how="left")

    matched = merged["home_xg"].notna().sum()
    total   = len(merged)
    logger.info(
        f"xG merge: {matched:,}/{total:,} matches matched "
        f"({matched/total:.1%} coverage)"
    )

    if matched / total < 0.5:
        logger.warning(
            "Low xG match rate — check TEAM_NAME_MAP for mismatches. "
            "Run with --debug to see unmatched teams."
        )

    return merged


# ═══════════════════════════════════════════════════════
# SECTION 5 — INCREMENTAL UPDATE (new season only)
# ═══════════════════════════════════════════════════════

def update_xg_incremental(league_key: "str | None" = None) -> pd.DataFrame:
    """
    Fetch only the current season's xG data and append to cached parquet.
    Call this daily/weekly to keep xG data fresh without re-scraping all history.

    Returns:
        Updated combined xG DataFrame.
    """
    current_year = our_season_to_understat(SEASONS.CURRENT)
    leagues      = [league_key] if league_key else list(UNDERSTAT_LEAGUE_MAP.keys())

    new_frames = []
    for lk in leagues:
        df = fetch_league_xg(lk, current_year)
        if df is not None:
            new_frames.append(df)

    if not new_frames:
        logger.warning("No new xG data fetched.")
        try:
            return load_xg_data()
        except FileNotFoundError:
            return pd.DataFrame()

    new_data = pd.concat(new_frames, ignore_index=True)

    # Load existing and merge (overwrite current season)
    try:
        existing = load_xg_data()
        existing = existing[existing["season_year"] != current_year]
        combined = pd.concat([existing, new_data], ignore_index=True)
    except FileNotFoundError:
        combined = new_data

    combined.sort_values(["league_key", "date"], inplace=True)
    combined.reset_index(drop=True, inplace=True)
    save_xg_data(combined)

    logger.info(f"xG incremental update complete: {len(new_data):,} new records")
    return combined


# ═══════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Fetch xG data from Understat.com"
    )
    parser.add_argument("--league",  default=None,
                        choices=list(UNDERSTAT_LEAGUE_MAP.keys()),
                        help="Single league to fetch")
    parser.add_argument("--season",  default=None,
                        help="Single season code e.g. 2324")
    parser.add_argument("--update",  action="store_true",
                        help="Incremental update (current season only)")
    parser.add_argument("--debug",   action="store_true",
                        help="Show unmatched team names")
    parser.add_argument("--debug-html",  action="store_true",
                        help="Save raw HTML of first page to /tmp/understat_debug.html for inspection")
    args = parser.parse_args()

    PATHS.create_all()

    if args.debug_html:
        logger.info("Debug mode: testing AJAX then HTML for EPL/2024 ...")

        result = _fetch_via_ajax("EPL", 2024)
        if result:
            logger.info(f"AJAX SUCCESS — {len(result)} matches returned")
            logger.info(f"First match keys: {list(result[0].keys())}")
            logger.info(f"Sample: {str(result[0])[:300]}")
        else:
            logger.warning("AJAX failed — trying HTML ...")
            result = _fetch_via_html("EPL", 2024)
            if result:
                logger.info(f"HTML SUCCESS — {len(result)} matches returned")
            else:
                logger.error(
                    "Both methods failed.\n"
                    "Check: 1) understat.com is accessible  2) Your firewall/VPN"
                )
        sys.exit(0)

    if args.update:
        update_xg_incremental(league_key=args.league)
    else:
        seasons = [args.season] if args.season else None
        leagues = [args.league] if args.league else None

        xg_df = fetch_all_xg(leagues=leagues, seasons=seasons)
        save_xg_data(xg_df)

        if args.debug:
            try:
                # engine intentionally omitted — pyarrow auto-detected, avoids Pylance false positive
                master = pd.read_parquet(PATHS.PROCESSED / "master.parquet")
                master_teams = set(master["home_team"]).union(master["away_team"])
                xg_teams     = set(xg_df["home_team"]).union(xg_df["away_team"])
                unmatched    = xg_teams - master_teams
                if unmatched:
                    logger.warning(f"Unmatched team names in xG data: {sorted(unmatched)}")
                    logger.info("Add these to TEAM_NAME_MAP in xg_scraper.py")
                else:
                    logger.info("All team names match master parquet ✓")
            except FileNotFoundError:
                logger.info("Master parquet not found — run update_data.py first")

        logger.info("Done. Run python src/update_data.py to rebuild features with xG.")